// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: scraper.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to CommandType:
	//
	//	*Command_GetId_
	//	*Command_GetVersion
	//	*Command_TriggerScraper
	CommandType   isCommand_CommandType `protobuf_oneof:"command_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Command) GetCommandType() isCommand_CommandType {
	if x != nil {
		return x.CommandType
	}
	return nil
}

func (x *Command) GetGetId_() *GetID {
	if x != nil {
		if x, ok := x.CommandType.(*Command_GetId_); ok {
			return x.GetId_
		}
	}
	return nil
}

func (x *Command) GetGetVersion() *GetVersion {
	if x != nil {
		if x, ok := x.CommandType.(*Command_GetVersion); ok {
			return x.GetVersion
		}
	}
	return nil
}

func (x *Command) GetTriggerScraper() *TriggerScraper {
	if x != nil {
		if x, ok := x.CommandType.(*Command_TriggerScraper); ok {
			return x.TriggerScraper
		}
	}
	return nil
}

type isCommand_CommandType interface {
	isCommand_CommandType()
}

type Command_GetId_ struct {
	GetId_ *GetID `protobuf:"bytes,2,opt,name=get_id,json=getId,proto3,oneof"`
}

type Command_GetVersion struct {
	GetVersion *GetVersion `protobuf:"bytes,3,opt,name=get_version,json=getVersion,proto3,oneof"`
}

type Command_TriggerScraper struct {
	TriggerScraper *TriggerScraper `protobuf:"bytes,4,opt,name=trigger_scraper,json=triggerScraper,proto3,oneof"`
}

func (*Command_GetId_) isCommand_CommandType() {}

func (*Command_GetVersion) isCommand_CommandType() {}

func (*Command_TriggerScraper) isCommand_CommandType() {}

type GetVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersion) Reset() {
	*x = GetVersion{}
	mi := &file_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersion) ProtoMessage() {}

func (x *GetVersion) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersion.ProtoReflect.Descriptor instead.
func (*GetVersion) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{1}
}

type GetID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetID) Reset() {
	*x = GetID{}
	mi := &file_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetID) ProtoMessage() {}

func (x *GetID) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetID.ProtoReflect.Descriptor instead.
func (*GetID) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{2}
}

type TriggerScraper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ScraperArgs:
	//
	//	*TriggerScraper_WebsiteScraper
	ScraperArgs   isTriggerScraper_ScraperArgs `protobuf_oneof:"scraper_args"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerScraper) Reset() {
	*x = TriggerScraper{}
	mi := &file_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScraper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScraper) ProtoMessage() {}

func (x *TriggerScraper) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScraper.ProtoReflect.Descriptor instead.
func (*TriggerScraper) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerScraper) GetScraperArgs() isTriggerScraper_ScraperArgs {
	if x != nil {
		return x.ScraperArgs
	}
	return nil
}

func (x *TriggerScraper) GetWebsiteScraper() *WebsiteScraperArgs {
	if x != nil {
		if x, ok := x.ScraperArgs.(*TriggerScraper_WebsiteScraper); ok {
			return x.WebsiteScraper
		}
	}
	return nil
}

type isTriggerScraper_ScraperArgs interface {
	isTriggerScraper_ScraperArgs()
}

type TriggerScraper_WebsiteScraper struct {
	WebsiteScraper *WebsiteScraperArgs `protobuf:"bytes,1,opt,name=website_scraper,json=websiteScraper,proto3,oneof"`
}

func (*TriggerScraper_WebsiteScraper) isTriggerScraper_ScraperArgs() {}

type Response struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId uint64                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to ResponseType:
	//
	//	*Response_Error
	//	*Response_Ok
	ResponseType  isResponse_ResponseType `protobuf_oneof:"response_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetCommandId() uint64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *Response) GetResponseType() isResponse_ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return nil
}

func (x *Response) GetError() *ResponseError {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Response) GetOk() *ResponseOk {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

type isResponse_ResponseType interface {
	isResponse_ResponseType()
}

type Response_Error struct {
	Error *ResponseError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type Response_Ok struct {
	Ok *ResponseOk `protobuf:"bytes,3,opt,name=ok,proto3,oneof"`
}

func (*Response_Error) isResponse_ResponseType() {}

func (*Response_Ok) isResponse_ResponseType() {}

type ResponseOk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ResponseOk_Id
	//	*ResponseOk_Version
	//	*ResponseOk_WebsiteScraper
	Response      isResponseOk_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseOk) Reset() {
	*x = ResponseOk{}
	mi := &file_scraper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseOk) ProtoMessage() {}

func (x *ResponseOk) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseOk.ProtoReflect.Descriptor instead.
func (*ResponseOk) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseOk) GetResponse() isResponseOk_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ResponseOk) GetId() *VersionID {
	if x != nil {
		if x, ok := x.Response.(*ResponseOk_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *ResponseOk) GetVersion() *VersionResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseOk_Version); ok {
			return x.Version
		}
	}
	return nil
}

func (x *ResponseOk) GetWebsiteScraper() *WebsiteScraperResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseOk_WebsiteScraper); ok {
			return x.WebsiteScraper
		}
	}
	return nil
}

type isResponseOk_Response interface {
	isResponseOk_Response()
}

type ResponseOk_Id struct {
	Id *VersionID `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type ResponseOk_Version struct {
	Version *VersionResponse `protobuf:"bytes,2,opt,name=version,proto3,oneof"`
}

type ResponseOk_WebsiteScraper struct {
	WebsiteScraper *WebsiteScraperResponse `protobuf:"bytes,3,opt,name=website_scraper,json=websiteScraper,proto3,oneof"`
}

func (*ResponseOk_Id) isResponseOk_Response() {}

func (*ResponseOk_Version) isResponseOk_Response() {}

func (*ResponseOk_WebsiteScraper) isResponseOk_Response() {}

type VersionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionID) Reset() {
	*x = VersionID{}
	mi := &file_scraper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionID) ProtoMessage() {}

func (x *VersionID) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionID.ProtoReflect.Descriptor instead.
func (*VersionID) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{6}
}

func (x *VersionID) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch         uint32                 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_scraper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{7}
}

func (x *VersionResponse) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *VersionResponse) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *VersionResponse) GetPatch() uint32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

type WebsiteScraperArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUrl     string                 `protobuf:"bytes,1,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsiteScraperArgs) Reset() {
	*x = WebsiteScraperArgs{}
	mi := &file_scraper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsiteScraperArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsiteScraperArgs) ProtoMessage() {}

func (x *WebsiteScraperArgs) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsiteScraperArgs.ProtoReflect.Descriptor instead.
func (*WebsiteScraperArgs) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{8}
}

func (x *WebsiteScraperArgs) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

type WebsiteScraperResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SourceUrl string                 `protobuf:"bytes,1,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	// Extracted readable content (markdown from dom_smoothie on the node).
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Full rendered page HTML (for same-origin link discovery during crawls).
	RenderedHtml  string `protobuf:"bytes,3,opt,name=rendered_html,json=renderedHtml,proto3" json:"rendered_html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsiteScraperResponse) Reset() {
	*x = WebsiteScraperResponse{}
	mi := &file_scraper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsiteScraperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsiteScraperResponse) ProtoMessage() {}

func (x *WebsiteScraperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsiteScraperResponse.ProtoReflect.Descriptor instead.
func (*WebsiteScraperResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{9}
}

func (x *WebsiteScraperResponse) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *WebsiteScraperResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WebsiteScraperResponse) GetRenderedHtml() string {
	if x != nil {
		return x.RenderedHtml
	}
	return ""
}

type ResponseError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ResponseError:
	//
	//	*ResponseError_UnknownCommandError
	//	*ResponseError_MissingCommandFieldError
	//	*ResponseError_WebsiteScraperError
	ResponseError isResponseError_ResponseError `protobuf_oneof:"response_error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseError) Reset() {
	*x = ResponseError{}
	mi := &file_scraper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseError) ProtoMessage() {}

func (x *ResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseError.ProtoReflect.Descriptor instead.
func (*ResponseError) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseError) GetResponseError() isResponseError_ResponseError {
	if x != nil {
		return x.ResponseError
	}
	return nil
}

func (x *ResponseError) GetUnknownCommandError() *UnknownCommandError {
	if x != nil {
		if x, ok := x.ResponseError.(*ResponseError_UnknownCommandError); ok {
			return x.UnknownCommandError
		}
	}
	return nil
}

func (x *ResponseError) GetMissingCommandFieldError() *MissingCommandFieldError {
	if x != nil {
		if x, ok := x.ResponseError.(*ResponseError_MissingCommandFieldError); ok {
			return x.MissingCommandFieldError
		}
	}
	return nil
}

func (x *ResponseError) GetWebsiteScraperError() *WebsiteScraperError {
	if x != nil {
		if x, ok := x.ResponseError.(*ResponseError_WebsiteScraperError); ok {
			return x.WebsiteScraperError
		}
	}
	return nil
}

type isResponseError_ResponseError interface {
	isResponseError_ResponseError()
}

type ResponseError_UnknownCommandError struct {
	UnknownCommandError *UnknownCommandError `protobuf:"bytes,1,opt,name=unknown_command_error,json=unknownCommandError,proto3,oneof"`
}

type ResponseError_MissingCommandFieldError struct {
	MissingCommandFieldError *MissingCommandFieldError `protobuf:"bytes,2,opt,name=missing_command_field_error,json=missingCommandFieldError,proto3,oneof"`
}

type ResponseError_WebsiteScraperError struct {
	WebsiteScraperError *WebsiteScraperError `protobuf:"bytes,3,opt,name=website_scraper_error,json=websiteScraperError,proto3,oneof"`
}

func (*ResponseError_UnknownCommandError) isResponseError_ResponseError() {}

func (*ResponseError_MissingCommandFieldError) isResponseError_ResponseError() {}

func (*ResponseError_WebsiteScraperError) isResponseError_ResponseError() {}

type WebsiteScraperError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to WebsiteError:
	//
	//	*WebsiteScraperError_Ratelimited
	//	*WebsiteScraperError_ScrapeFailed
	WebsiteError  isWebsiteScraperError_WebsiteError `protobuf_oneof:"website_error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsiteScraperError) Reset() {
	*x = WebsiteScraperError{}
	mi := &file_scraper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsiteScraperError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsiteScraperError) ProtoMessage() {}

func (x *WebsiteScraperError) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsiteScraperError.ProtoReflect.Descriptor instead.
func (*WebsiteScraperError) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{11}
}

func (x *WebsiteScraperError) GetWebsiteError() isWebsiteScraperError_WebsiteError {
	if x != nil {
		return x.WebsiteError
	}
	return nil
}

func (x *WebsiteScraperError) GetRatelimited() *Ratelimited {
	if x != nil {
		if x, ok := x.WebsiteError.(*WebsiteScraperError_Ratelimited); ok {
			return x.Ratelimited
		}
	}
	return nil
}

func (x *WebsiteScraperError) GetScrapeFailed() *ScrapeFailed {
	if x != nil {
		if x, ok := x.WebsiteError.(*WebsiteScraperError_ScrapeFailed); ok {
			return x.ScrapeFailed
		}
	}
	return nil
}

type isWebsiteScraperError_WebsiteError interface {
	isWebsiteScraperError_WebsiteError()
}

type WebsiteScraperError_Ratelimited struct {
	Ratelimited *Ratelimited `protobuf:"bytes,1,opt,name=ratelimited,proto3,oneof"`
}

type WebsiteScraperError_ScrapeFailed struct {
	ScrapeFailed *ScrapeFailed `protobuf:"bytes,2,opt,name=scrape_failed,json=scrapeFailed,proto3,oneof"`
}

func (*WebsiteScraperError_Ratelimited) isWebsiteScraperError_WebsiteError() {}

func (*WebsiteScraperError_ScrapeFailed) isWebsiteScraperError_WebsiteError() {}

type ScrapeFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeFailed) Reset() {
	*x = ScrapeFailed{}
	mi := &file_scraper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeFailed) ProtoMessage() {}

func (x *ScrapeFailed) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeFailed.ProtoReflect.Descriptor instead.
func (*ScrapeFailed) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{12}
}

func (x *ScrapeFailed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Ratelimited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ratelimited) Reset() {
	*x = Ratelimited{}
	mi := &file_scraper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ratelimited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ratelimited) ProtoMessage() {}

func (x *Ratelimited) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ratelimited.ProtoReflect.Descriptor instead.
func (*Ratelimited) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{13}
}

type UnknownCommandError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnknownCommandError) Reset() {
	*x = UnknownCommandError{}
	mi := &file_scraper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnknownCommandError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownCommandError) ProtoMessage() {}

func (x *UnknownCommandError) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownCommandError.ProtoReflect.Descriptor instead.
func (*UnknownCommandError) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{14}
}

type MissingCommandFieldError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissingCommandFieldError) Reset() {
	*x = MissingCommandFieldError{}
	mi := &file_scraper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissingCommandFieldError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissingCommandFieldError) ProtoMessage() {}

func (x *MissingCommandFieldError) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissingCommandFieldError.ProtoReflect.Descriptor instead.
func (*MissingCommandFieldError) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{15}
}

var File_scraper_proto protoreflect.FileDescriptor

const file_scraper_proto_rawDesc = "" +
	"\n" +
	"\rscraper.proto\x12\vnodescraper\"\xda\x01\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12+\n" +
	"\x06get_id\x18\x02 \x01(\v2\x12.nodescraper.GetIDH\x00R\x05getId\x12:\n" +
	"\vget_version\x18\x03 \x01(\v2\x17.nodescraper.GetVersionH\x00R\n" +
	"getVersion\x12F\n" +
	"\x0ftrigger_scraper\x18\x04 \x01(\v2\x1b.nodescraper.TriggerScraperH\x00R\x0etriggerScraperB\x0e\n" +
	"\fcommand_type\"\f\n" +
	"\n" +
	"GetVersion\"\a\n" +
	"\x05GetID\"l\n" +
	"\x0eTriggerScraper\x12J\n" +
	"\x0fwebsite_scraper\x18\x01 \x01(\v2\x1f.nodescraper.WebsiteScraperArgsH\x00R\x0ewebsiteScraperB\x0e\n" +
	"\fscraper_args\"\x99\x01\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x04R\tcommandId\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1a.nodescraper.ResponseErrorH\x00R\x05error\x12)\n" +
	"\x02ok\x18\x03 \x01(\v2\x17.nodescraper.ResponseOkH\x00R\x02okB\x0f\n" +
	"\rresponse_type\"\xcc\x01\n" +
	"\n" +
	"ResponseOk\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x16.nodescraper.VersionIDH\x00R\x02id\x128\n" +
	"\aversion\x18\x02 \x01(\v2\x1c.nodescraper.VersionResponseH\x00R\aversion\x12N\n" +
	"\x0fwebsite_scraper\x18\x03 \x01(\v2#.nodescraper.WebsiteScraperResponseH\x00R\x0ewebsiteScraperB\n" +
	"\n" +
	"\bresponse\"\x1b\n" +
	"\tVersionID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"S\n" +
	"\x0fVersionResponse\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\rR\x05patch\"3\n" +
	"\x12WebsiteScraperArgs\x12\x1d\n" +
	"\n" +
	"source_url\x18\x01 \x01(\tR\tsourceUrl\"v\n" +
	"\x16WebsiteScraperResponse\x12\x1d\n" +
	"\n" +
	"source_url\x18\x01 \x01(\tR\tsourceUrl\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12#\n" +
	"\rrendered_html\x18\x03 \x01(\tR\frenderedHtml\"\xb9\x02\n" +
	"\rResponseError\x12V\n" +
	"\x15unknown_command_error\x18\x01 \x01(\v2 .nodescraper.UnknownCommandErrorH\x00R\x13unknownCommandError\x12f\n" +
	"\x1bmissing_command_field_error\x18\x02 \x01(\v2%.nodescraper.MissingCommandFieldErrorH\x00R\x18missingCommandFieldError\x12V\n" +
	"\x15website_scraper_error\x18\x03 \x01(\v2 .nodescraper.WebsiteScraperErrorH\x00R\x13websiteScraperErrorB\x10\n" +
	"\x0eresponse_error\"\xa6\x01\n" +
	"\x13WebsiteScraperError\x12<\n" +
	"\vratelimited\x18\x01 \x01(\v2\x18.nodescraper.RatelimitedH\x00R\vratelimited\x12@\n" +
	"\rscrape_failed\x18\x02 \x01(\v2\x19.nodescraper.ScrapeFailedH\x00R\fscrapeFailedB\x0f\n" +
	"\rwebsite_error\"(\n" +
	"\fScrapeFailed\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\r\n" +
	"\vRatelimited\"\x15\n" +
	"\x13UnknownCommandError\"\x1a\n" +
	"\x18MissingCommandFieldErrorB\vZ\t/messagesb\x06proto3"

var (
	file_scraper_proto_rawDescOnce sync.Once
	file_scraper_proto_rawDescData []byte
)

func file_scraper_proto_rawDescGZIP() []byte {
	file_scraper_proto_rawDescOnce.Do(func() {
		file_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)))
	})
	return file_scraper_proto_rawDescData
}

var file_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_scraper_proto_goTypes = []any{
	(*Command)(nil),                  // 0: nodescraper.Command
	(*GetVersion)(nil),               // 1: nodescraper.GetVersion
	(*GetID)(nil),                    // 2: nodescraper.GetID
	(*TriggerScraper)(nil),           // 3: nodescraper.TriggerScraper
	(*Response)(nil),                 // 4: nodescraper.Response
	(*ResponseOk)(nil),               // 5: nodescraper.ResponseOk
	(*VersionID)(nil),                // 6: nodescraper.VersionID
	(*VersionResponse)(nil),          // 7: nodescraper.VersionResponse
	(*WebsiteScraperArgs)(nil),       // 8: nodescraper.WebsiteScraperArgs
	(*WebsiteScraperResponse)(nil),   // 9: nodescraper.WebsiteScraperResponse
	(*ResponseError)(nil),            // 10: nodescraper.ResponseError
	(*WebsiteScraperError)(nil),      // 11: nodescraper.WebsiteScraperError
	(*ScrapeFailed)(nil),             // 12: nodescraper.ScrapeFailed
	(*Ratelimited)(nil),              // 13: nodescraper.Ratelimited
	(*UnknownCommandError)(nil),      // 14: nodescraper.UnknownCommandError
	(*MissingCommandFieldError)(nil), // 15: nodescraper.MissingCommandFieldError
}
var file_scraper_proto_depIdxs = []int32{
	2,  // 0: nodescraper.Command.get_id:type_name -> nodescraper.GetID
	1,  // 1: nodescraper.Command.get_version:type_name -> nodescraper.GetVersion
	3,  // 2: nodescraper.Command.trigger_scraper:type_name -> nodescraper.TriggerScraper
	8,  // 3: nodescraper.TriggerScraper.website_scraper:type_name -> nodescraper.WebsiteScraperArgs
	10, // 4: nodescraper.Response.error:type_name -> nodescraper.ResponseError
	5,  // 5: nodescraper.Response.ok:type_name -> nodescraper.ResponseOk
	6,  // 6: nodescraper.ResponseOk.id:type_name -> nodescraper.VersionID
	7,  // 7: nodescraper.ResponseOk.version:type_name -> nodescraper.VersionResponse
	9,  // 8: nodescraper.ResponseOk.website_scraper:type_name -> nodescraper.WebsiteScraperResponse
	14, // 9: nodescraper.ResponseError.unknown_command_error:type_name -> nodescraper.UnknownCommandError
	15, // 10: nodescraper.ResponseError.missing_command_field_error:type_name -> nodescraper.MissingCommandFieldError
	11, // 11: nodescraper.ResponseError.website_scraper_error:type_name -> nodescraper.WebsiteScraperError
	13, // 12: nodescraper.WebsiteScraperError.ratelimited:type_name -> nodescraper.Ratelimited
	12, // 13: nodescraper.WebsiteScraperError.scrape_failed:type_name -> nodescraper.ScrapeFailed
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_scraper_proto_init() }
func file_scraper_proto_init() {
	if File_scraper_proto != nil {
		return
	}
	file_scraper_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_GetId_)(nil),
		(*Command_GetVersion)(nil),
		(*Command_TriggerScraper)(nil),
	}
	file_scraper_proto_msgTypes[3].OneofWrappers = []any{
		(*TriggerScraper_WebsiteScraper)(nil),
	}
	file_scraper_proto_msgTypes[4].OneofWrappers = []any{
		(*Response_Error)(nil),
		(*Response_Ok)(nil),
	}
	file_scraper_proto_msgTypes[5].OneofWrappers = []any{
		(*ResponseOk_Id)(nil),
		(*ResponseOk_Version)(nil),
		(*ResponseOk_WebsiteScraper)(nil),
	}
	file_scraper_proto_msgTypes[10].OneofWrappers = []any{
		(*ResponseError_UnknownCommandError)(nil),
		(*ResponseError_MissingCommandFieldError)(nil),
		(*ResponseError_WebsiteScraperError)(nil),
	}
	file_scraper_proto_msgTypes[11].OneofWrappers = []any{
		(*WebsiteScraperError_Ratelimited)(nil),
		(*WebsiteScraperError_ScrapeFailed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scraper_proto_goTypes,
		DependencyIndexes: file_scraper_proto_depIdxs,
		MessageInfos:      file_scraper_proto_msgTypes,
	}.Build()
	File_scraper_proto = out.File
	file_scraper_proto_goTypes = nil
	file_scraper_proto_depIdxs = nil
}
