name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work

      - name: Build all deployments
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt install -y protobuf-compiler
          rustup target add aarch64-unknown-linux-gnu
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go build -ldflags "-s -w" -o "main"
          cd nodescraper-rs && cargo build --release --target=aarch64-unknown-linux-gnu

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            main
            nodescraper-rs/target/aarch64-unknown-linux-gnu/release/nodescraper-rs
          generate_release_notes: true
