name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work

      - name: Setup environment
        run: |
          sudo dpkg --add-architecture arm64
          sudo sed -i '/^Types: deb/a Architectures: amd64' /etc/apt/sources.list.d/ubuntu.sources
          echo -e "Types: deb\nURIs: http://ports.ubuntu.com/ubuntu-ports/\nSuites: $(lsb_release -cs) $(lsb_release -cs)-updates $(lsb_release -cs)-backports $(lsb_release -cs)-security\nComponents: main restricted universe multiverse\nArchitectures: arm64\nSigned-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg" | sudo tee /etc/apt/sources.list.d/arm64.sources > /dev/null
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libfontconfig1-dev pkg-config fontconfig protobuf-compiler libfontconfig1-dev:arm64
          rustup target add aarch64-unknown-linux-gnu
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Build Seer Binary
        run: |
          go build -ldflags "-s -w" -o "main"
      - name: Build nodescraper for amd64
        env:
          REMOTE_URL: "wss://seer.lariv.in/fleet/websocket"
        run: |
          cd nodescraper-rs for amd64
          cargo build --release 
          cd ..
      - name: Build nodescraper for arm64
        env:
          REMOTE_URL: "wss://seer.lariv.in/fleet/websocket"
          PKG_CONFIG_DIR: ""
          PKG_CONFIG_LIBDIR: "/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig"
          PKG_CONFIG_SYSROOT_DIR: "/"
          PKG_CONFIG_ALLOW_CROSS: "1"
        run: |
          cargo build --release --target=aarch64-unknown-linux-gnu
          cd ..
      - name: Prepare binaries for upload to release
        run: |
          cp nodescraper-rs/target/aarch64-unknown-linux-gnu/release/nodescraper-rs nodescraper-linux-aarch64
          cp nodescraper-rs/target/release/nodescraper-rs nodescraper-linux-amd64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            main
            nodescraper-linux-aarch64
            nodescraper-linux-amd64
          generate_release_notes: true
